window.EVENTS_DATA = 
{
  "meta": {
    "compiled_at": "2026-05-21",
    "target_admission_year": "2027학년도",
    "scope": "수도권 인서울/중하위권 + 거점국립대 + 지방 사립 (문과 우선)",
    "note": "수집일 기준 공개 일정만 반영. TBD 는 작년 패턴 기준 시기 추정이며, 확정되면 갱신 필요. 5월 21일 이전 종료된 행사는 제외."
  },
  "events": [
    {
      "university": "코엑스 / 한국대학교육협의회",
      "event_name": "2027학년도 수시 대학입학정보박람회",
      "date": "2026-07-24",
      "date_end": "2026-07-26",
      "time": "10:00-17:00",
      "location": "코엑스(서울 강남구) 1층 A홀·B홀",
      "format": "오프라인",
      "audience": ["수험생", "학부모", "교사"],
      "registration_required": true,
      "registration_deadline": "2026-07-26",
      "registration_url": "https://univexpo.kr/sub-04-01?hl=ko",
      "info_url": "https://univexpo.kr/sub-2026-fair?hl=ko",
      "fee": "무료(사전예매)",
      "notes": "전국 대학 부스 + 1:1 상담 + 전공 설명. 사전예매 6/30 00:00 ~ 7/26 11:59. 매년 가장 큰 박람회 — 한 번 가면 인서울+지방대 한 곳에서 비교 가능. 강추",
      "source_url": "https://univexpo.kr/",
      "tier": "박람회",
      "humanities_relevant": true,
      "tags": ["박람회", "필수참여추천"],
      "priority": "high"
    },
    {
      "university": "코엑스 / 한국대학교육협의회",
      "event_name": "2027학년도 정시 대학입학정보박람회 (예상)",
      "date": "2026-12-18",
      "date_end": "2026-12-20",
      "time": "10:00-17:00",
      "location": "코엑스(서울 강남구) 1층 A홀 (예상)",
      "format": "오프라인",
      "audience": ["수험생", "학부모"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://univexpo.kr/",
      "fee": "무료",
      "notes": "수능 후 정시 지원 직전 대규모 박람회. 작년 일정(2025-12-18~20) 기준으로 추정 — 11월 중 공식 발표 예정",
      "source_url": "https://www.coex.co.kr/exhibitions/2026%ED%95%99%EB%85%84%EB%8F%84-%EC%A0%95%EC%8B%9C-%EB%8C%80%ED%95%99%EC%9E%85%ED%95%99%EC%A0%95%EB%B3%B4%EB%B0%95%EB%9E%8C%ED%9A%8C/",
      "tier": "박람회",
      "humanities_relevant": true,
      "tags": ["박람회", "정시", "TBD"],
      "priority": "high"
    },
    {
      "university": "중앙대학교",
      "event_name": "2027학년도 전국 입학설명회 (CAU × Lotte CINEMA)",
      "date": "2026-05-21",
      "date_end": "2026-06-30",
      "time": "TBD",
      "location": "전국 롯데시네마 (서울/인천/경기/대전/대구/부산/광주/창원/제주)",
      "format": "오프라인",
      "audience": ["수험생", "학부모"],
      "registration_required": true,
      "registration_deadline": "각 회차별 사전 신청",
      "registration_url": "https://admission.cau.ac.kr/",
      "info_url": "https://admission.cau.ac.kr/resources/intro_2027_admission.html",
      "fee": "무료",
      "notes": "5~6월 진행. 영화관 대형 화면으로 입학사정관 직접 설명. 지역별 일정은 중앙대 입학처 공지 확인",
      "source_url": "https://admission.cau.ac.kr/resources/intro_2027_admission.html",
      "tier": "인서울_중경외시",
      "humanities_relevant": true,
      "tags": ["전국순회", "영화관"],
      "priority": "high"
    },
    {
      "university": "중앙대학교",
      "event_name": "전국 고교 방문 설명회 (교사 동반 가능)",
      "date": "2026-05-21",
      "date_end": "2026-07-03",
      "time": "수/목/금",
      "location": "전국 고등학교",
      "format": "오프라인",
      "audience": ["교사", "수험생"],
      "registration_required": true,
      "registration_deadline": "2026-04-08 (마감)",
      "registration_url": "https://admission.cau.ac.kr/",
      "info_url": "https://admission.cau.ac.kr/resources/intro_2027_admission.html",
      "fee": "무료",
      "notes": "학교 단위 신청 — 따님 학교에서 신청했는지 담임 통해 확인",
      "source_url": "https://admission.cau.ac.kr/resources/intro_2027_admission.html",
      "tier": "인서울_중경외시",
      "humanities_relevant": true,
      "tags": ["고교방문"],
      "priority": "medium"
    },
    {
      "university": "고려대학교",
      "event_name": "본교 입학설명회 + 지역거점 입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "안암캠퍼스 / 지역 거점도시",
      "format": "오프라인",
      "audience": ["수험생", "학부모", "교사"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://oku.korea.ac.kr/",
      "fee": "무료",
      "notes": "예년 6~7월 본교/지역거점 설명회 개최. 입학처 공지사항 수시 체크 필요 (02-3290-5161~3)",
      "source_url": "https://oku.korea.ac.kr/oku/index.do",
      "tier": "인서울_SKY",
      "humanities_relevant": true,
      "tags": ["TBD", "확인필요"],
      "priority": "high"
    },
    {
      "university": "연세대학교",
      "event_name": "지역거점 입학설명회 (5월 회차 종료, 추가 회차 가능성)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "전국 거점도시",
      "format": "오프라인/온라인 혼합",
      "audience": ["수험생", "학부모"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.yonsei.ac.kr/seoul/",
      "fee": "무료",
      "notes": "5월 회차(5/9~30)는 대부분 종료. 6월 이후 추가 회차나 본교 설명회 확인 권장. 02-2123-4131",
      "source_url": "https://admission.yonsei.ac.kr/seoul/admission/html/counsel/calendar.asp",
      "tier": "인서울_SKY",
      "humanities_relevant": true,
      "tags": ["TBD", "확인필요"],
      "priority": "high"
    },
    {
      "university": "서울대학교",
      "event_name": "학부모 교육 프로그램 + 입학사정관 출장 설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "관악캠퍼스 / 자치구청 (예년 관악구청 대강당 등)",
      "format": "오프라인/온라인",
      "audience": ["수험생", "학부모"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.snu.ac.kr/",
      "fee": "무료",
      "notes": "예년 6월·하반기 학부모 대상 출장 설명회 진행. 입학본부 공지 + 자치구청 안내 동시 확인. 02-880-5114",
      "source_url": "https://admission.snu.ac.kr/",
      "tier": "인서울_SKY",
      "humanities_relevant": true,
      "tags": ["TBD", "확인필요"],
      "priority": "high"
    },
    {
      "university": "서강대학교",
      "event_name": "수시 학부모 설명회 + 박람회 참가",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "서강대 캠퍼스 / COEX 박람회",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.sogang.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월 학부모 설명회 개최. 입학처 공지 확인 필요",
      "source_url": "https://admission.sogang.ac.kr/enter/html/counsel/notice.asp",
      "tier": "인서울_서성한",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "high"
    },
    {
      "university": "성균관대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "인문사회과학캠퍼스(혜화/명륜) 또는 자연과학캠퍼스(수원)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.skku.edu/",
      "fee": "무료",
      "notes": "예년 6~7월 본교 설명회. 문과는 인사캠 이용. 입학처 공지 모니터링",
      "source_url": "https://admission.skku.edu/",
      "tier": "인서울_서성한",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "high"
    },
    {
      "university": "한양대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "서울캠퍼스(왕십리) / ERICA(안산)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://go.hanyang.ac.kr/",
      "fee": "무료",
      "notes": "예년 6~8월 학부모/수험생 설명회 + 캠퍼스투어",
      "source_url": "https://go.hanyang.ac.kr/",
      "tier": "인서울_서성한",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "high"
    },
    {
      "university": "경희대학교",
      "event_name": "권역별 설명회 + 캠퍼스 본교 설명회 (5월 권역 일부 종료)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "전국 권역별 + 서울캠퍼스/국제캠퍼스",
      "format": "오프라인",
      "audience": ["수험생", "학부모", "교사"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://iphak.khu.ac.kr/",
      "fee": "무료",
      "notes": "5/12~29 권역별 회차는 종료. 추가 본교 설명회 확인",
      "source_url": "https://iphak.khu.ac.kr/",
      "tier": "인서울_중경외시",
      "humanities_relevant": true,
      "tags": ["TBD", "확인필요"],
      "priority": "high"
    },
    {
      "university": "한국외국어대학교",
      "event_name": "입학설명회 (TBD) — 문과 강세 학교",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "서울캠퍼스(이문동) / 글로벌캠퍼스(용인)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://adms.hufs.ac.kr/",
      "fee": "무료",
      "notes": "외국어/사회과학 계열 — 문과 따님 관심 권장. 예년 6~8월 설명회",
      "source_url": "https://adms.hufs.ac.kr/index.do",
      "tier": "인서울_중경외시",
      "humanities_relevant": true,
      "tags": ["TBD", "문과강세"],
      "priority": "high"
    },
    {
      "university": "서울시립대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "서울시립대 캠퍼스(전농)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://enter.uos.ac.kr/",
      "fee": "무료",
      "notes": "공립대 등록금 강점. 도시행정/도시사회 등 문과 인기. 예년 7~8월 설명회",
      "source_url": "https://enter.uos.ac.kr/",
      "tier": "인서울_중경외시",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "high"
    },
    {
      "university": "건국대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "건국대 캠퍼스(능동)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://www.konkuk.ac.kr/admission/",
      "fee": "무료",
      "notes": "예년 7~9월 설명회. 경영/문과대 인기",
      "source_url": "https://enter.konkuk.ac.kr/",
      "tier": "인서울_건동홍",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "medium"
    },
    {
      "university": "동국대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "동국대 캠퍼스(필동)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.dongguk.edu/",
      "fee": "무료",
      "notes": "문과 강세. 예년 7~8월 설명회",
      "source_url": "https://ipsi.dongguk.edu/",
      "tier": "인서울_건동홍",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "medium"
    },
    {
      "university": "홍익대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "홍익대 캠퍼스(상수)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ibsi.hongik.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~8월 설명회",
      "source_url": "https://ibsi.hongik.ac.kr/",
      "tier": "인서울_건동홍",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "medium"
    },
    {
      "university": "이화여자대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "이화여대 캠퍼스(대현)",
      "format": "오프라인/온라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.ewha.ac.kr/admission/html/ewharo/seminar.asp",
      "fee": "무료",
      "notes": "예년 7~9월 설명회 + 모의논술. 문과 비중 높은 학교 — 따님 적합",
      "source_url": "https://admission.ewha.ac.kr/admission/html/ewharo/seminar.asp",
      "tier": "인서울_여대",
      "humanities_relevant": true,
      "tags": ["TBD", "여대"],
      "priority": "high"
    },
    {
      "university": "숙명여자대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "숙명여대 캠퍼스(청파)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.sookmyung.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월 설명회",
      "source_url": "https://ipsi.sookmyung.ac.kr/",
      "tier": "인서울_여대",
      "humanities_relevant": true,
      "tags": ["TBD", "여대"],
      "priority": "high"
    },
    {
      "university": "숭실대학교",
      "event_name": "고교 방문 설명회",
      "date": "2026-05-21",
      "date_end": "2026-07-15",
      "time": "TBD",
      "location": "전국 고등학교",
      "format": "오프라인",
      "audience": ["수험생"],
      "registration_required": true,
      "registration_deadline": "각 회차별",
      "registration_url": "https://iphak.ssu.ac.kr/",
      "info_url": "https://iphak.ssu.ac.kr/",
      "fee": "무료",
      "notes": "학교 단위 신청 — 담임 통해 신청 확인",
      "source_url": "https://iphak.ssu.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["고교방문"],
      "priority": "medium"
    },
    {
      "university": "가톨릭대학교",
      "event_name": "고교 방문 설명회 + 교사간담회",
      "date": "TBD",
      "date_end": "2026-07-16",
      "time": "TBD",
      "location": "전국 고등학교",
      "format": "오프라인",
      "audience": ["교사", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "https://iphak.catholic.ac.kr/",
      "info_url": "https://iphak.catholic.ac.kr/",
      "fee": "무료",
      "notes": "~7/16까지 진행. 학교 단위 신청",
      "source_url": "https://www.veritas-a.com/news/articleView.html?idxno=606412",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["고교방문"],
      "priority": "low"
    },
    {
      "university": "인하대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "인하대 캠퍼스(인천 용현)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.inha.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월 설명회",
      "source_url": "https://admission.inha.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "medium"
    },
    {
      "university": "아주대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "아주대 캠퍼스(수원)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.ajou.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~8월 설명회",
      "source_url": "https://admission.ajou.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "medium"
    },
    {
      "university": "가천대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "가천대 글로벌캠퍼스(성남)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.gachon.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월 설명회",
      "source_url": "https://admission.gachon.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "단국대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "죽전캠퍼스(용인) / 천안캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.dankook.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월",
      "source_url": "https://ipsi.dankook.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "세종대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "세종대 캠퍼스(군자)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.sejong.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월",
      "source_url": "https://ipsi.sejong.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "광운대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "광운대 캠퍼스(노원)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://iphak.kw.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~8월",
      "source_url": "https://iphak.kw.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "국민대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "국민대 캠퍼스(정릉)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.kookmin.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월",
      "source_url": "https://ipsi.kookmin.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "명지대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "서울캠퍼스(인문) / 자연캠퍼스(용인)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.mju.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~8월",
      "source_url": "https://ipsi.mju.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "성신여자대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "성신여대 운정녹지캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.sungshin.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월. 여대",
      "source_url": "https://ipsi.sungshin.ac.kr/",
      "tier": "수도권_여대",
      "humanities_relevant": true,
      "tags": ["TBD", "여대"],
      "priority": "low"
    },
    {
      "university": "서울여자대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "서울여대 캠퍼스(공릉)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.swu.ac.kr/",
      "fee": "무료",
      "notes": "예년 7~9월",
      "source_url": "https://admission.swu.ac.kr/",
      "tier": "수도권_여대",
      "humanities_relevant": true,
      "tags": ["TBD", "여대"],
      "priority": "low"
    },
    {
      "university": "덕성여자대학교",
      "event_name": "온라인 모의논술고사 (수시 논술전형 대비)",
      "date": "2026-07-10",
      "date_end": "2026-07-13",
      "time": "온라인",
      "location": "온라인",
      "format": "온라인",
      "audience": ["수험생"],
      "registration_required": true,
      "registration_deadline": "TBD (7월 초)",
      "registration_url": "https://admission.duksung.ac.kr/",
      "info_url": "https://admission.duksung.ac.kr/",
      "fee": "무료",
      "notes": "논술전형 지원 예정 시 필참. 사전등록 후 응시",
      "source_url": "https://www.adiga.kr/uct/gdf/univEventView.do?menuId=PCUCTGDF1000",
      "tier": "수도권_여대",
      "humanities_relevant": true,
      "tags": ["모의논술", "여대", "확정일정"],
      "priority": "medium"
    },
    {
      "university": "서울대 (관악구청 주관)",
      "event_name": "관악구 서울대 입학설명회 (예년 패턴)",
      "date": "TBD",
      "date_end": "",
      "time": "예년 18:30~20:30",
      "location": "관악구청 대강당(예상)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://www.gwanak.go.kr/",
      "fee": "무료",
      "notes": "예년(2025) 6/4 개최. 입학사정관 직강 + Q&A. 관악구 거주 학부모 우선",
      "source_url": "https://biz.heraldcorp.com/article/10500491",
      "tier": "인서울_SKY",
      "humanities_relevant": true,
      "tags": ["TBD", "지자체주관"],
      "priority": "medium"
    },
    {
      "university": "강원대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "춘천캠퍼스 / 삼척캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.kangwon.ac.kr/",
      "fee": "무료",
      "notes": "거점국립대. 예년 7~9월",
      "source_url": "https://admission.kangwon.ac.kr/",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["TBD", "거점국립대"],
      "priority": "medium"
    },
    {
      "university": "충북대학교",
      "event_name": "2026 입학설명회 (월별 캘린더 운영)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "충북대 캠퍼스(청주) + 고교방문 + 온라인(Zoom)",
      "format": "하이브리드",
      "audience": ["학부모", "수험생", "교사"],
      "registration_required": true,
      "registration_deadline": "각 회차별",
      "registration_url": "https://ipsi.chungbuk.ac.kr/kor/presentation/calendar.do",
      "info_url": "https://ipsi.chungbuk.ac.kr/kor/presentation/calendar.do",
      "fee": "무료",
      "notes": "거점국립대. 캘린더로 회차별 신청 가능 — 가장 체계적인 거점국립대. ☎ 043-261-3831",
      "source_url": "https://ipsi.chungbuk.ac.kr/kor/presentation/calendar.do",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["거점국립대", "캘린더운영"],
      "priority": "high"
    },
    {
      "university": "충남대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "대전캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.cnu.ac.kr/",
      "fee": "무료",
      "notes": "거점국립대",
      "source_url": "https://ipsi.cnu.ac.kr/",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["TBD", "거점국립대"],
      "priority": "medium"
    },
    {
      "university": "전북대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "전주캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://enter.jbnu.ac.kr/",
      "fee": "무료",
      "notes": "거점국립대",
      "source_url": "https://enter.jbnu.ac.kr/",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["TBD", "거점국립대"],
      "priority": "medium"
    },
    {
      "university": "전남대학교",
      "event_name": "입학설명회 (TBD, events.jnu.ac.kr 캘린더 확인)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "광주캠퍼스 / 여수캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "https://events.jnu.ac.kr/",
      "info_url": "https://www.jnu.ac.kr/",
      "fee": "무료",
      "notes": "거점국립대. 일정은 events.jnu.ac.kr 매일 갱신",
      "source_url": "https://events.jnu.ac.kr/Schedule.aspx?mode=1",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["TBD", "거점국립대"],
      "priority": "medium"
    },
    {
      "university": "경북대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "대구캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://enter.knu.ac.kr/",
      "fee": "무료",
      "notes": "거점국립대",
      "source_url": "https://enter.knu.ac.kr/",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["TBD", "거점국립대"],
      "priority": "medium"
    },
    {
      "university": "부산대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "부산캠퍼스(장전)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://go.pusan.ac.kr/",
      "fee": "무료",
      "notes": "거점국립대",
      "source_url": "https://go.pusan.ac.kr/",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["TBD", "거점국립대"],
      "priority": "medium"
    },
    {
      "university": "경상국립대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "진주캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.gnu.ac.kr/",
      "fee": "무료",
      "notes": "거점국립대",
      "source_url": "https://admission.gnu.ac.kr/",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["TBD", "거점국립대"],
      "priority": "medium"
    },
    {
      "university": "제주대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "제주캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.jejunu.ac.kr/",
      "fee": "무료",
      "notes": "거점국립대",
      "source_url": "https://admission.jejunu.ac.kr/",
      "tier": "거점국립대",
      "humanities_relevant": true,
      "tags": ["TBD", "거점국립대"],
      "priority": "low"
    },
    {
      "university": "EBSi (안동)",
      "event_name": "2026 EBS 입시전략설명회 IN 안동 + 진학드림캠퍼스",
      "date": "2026-07-05",
      "date_end": "",
      "time": "TBD",
      "location": "안동시 (장소 별도 공지)",
      "format": "오프라인",
      "audience": ["수험생", "학부모"],
      "registration_required": true,
      "registration_deadline": "사전신청",
      "registration_url": "",
      "info_url": "https://about.ebs.co.kr/board/bbs?boardTypeId=1&boardId=31",
      "fee": "무료",
      "notes": "1:1 대입상담 + 국·영·수 학습전략 + 진학설명회 + 진로특강. 사전신청 필수",
      "source_url": "https://about.ebs.co.kr/board/bbs?boardTypeId=1&boardId=31",
      "tier": "전국_박람회",
      "humanities_relevant": true,
      "tags": ["EBS", "지방"],
      "priority": "medium"
    },
    {
      "university": "EBSi",
      "event_name": "EBS 입시설명회 (전국 순회)",
      "date": "TBD",
      "date_end": "",
      "time": "TBD",
      "location": "전국 권역별 (교육청 공동주관)",
      "format": "오프라인/온라인",
      "audience": ["수험생", "학부모"],
      "registration_required": true,
      "registration_deadline": "회차별",
      "registration_url": "https://www.ebsi.co.kr/ebs/ent/enta/retrieveIpsiBriefingList.ebs",
      "info_url": "https://www.ebsi.co.kr/ebs/ent/enta/retrieveIpsiBriefingList.ebs",
      "fee": "무료",
      "notes": "EBSi 페이지에서 전국 432+ 회차 등록. 지역별로 검색 가능",
      "source_url": "https://www.ebsi.co.kr/ebs/ent/enta/retrieveIpsiBriefingList.ebs",
      "tier": "전국_박람회",
      "humanities_relevant": true,
      "tags": ["EBS", "수시갱신"],
      "priority": "medium"
    },
    {
      "university": "수원대학교",
      "event_name": "2027학년도 모의 논술고사 + 입시설명회",
      "date": "TBD",
      "date_note": "예년 6~7월 모의논술고사. 2027학년도 모의논술 모범답안 5/11 공개 (회차 종료) — 추가 회차 가능성",
      "time": "TBD",
      "location": "수원대 캠퍼스(화성 봉담)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.suwon.ac.kr/",
      "fee": "무료",
      "notes": "이미 1차 모의논술 진행 — 2차 일정 또는 학부모 설명회 별도 공지 예정. ☎ 031-229-8420~2",
      "source_url": "https://ipsi.suwon.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "medium"
    },
    {
      "university": "안양대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월 본교 설명회",
      "time": "TBD",
      "location": "안양대 캠퍼스(안양) / 강화캠퍼스",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.anyang.ac.kr/",
      "fee": "무료",
      "notes": "수도권 중하위 사립. 문과 일부 학과 강세",
      "source_url": "https://ipsi.anyang.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "삼육대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월 본교 설명회",
      "time": "TBD",
      "location": "삼육대 캠퍼스(서울 노원)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.syu.ac.kr/",
      "fee": "무료",
      "notes": "노원 위치이나 인서울 주요권 아님. 보건·간호·신학 강세",
      "source_url": "https://ipsi.syu.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "강남대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "강남대 캠퍼스(용인 기흥)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.kangnam.ac.kr/",
      "fee": "무료",
      "notes": "사회복지·실버산업·평화통일 등 문과 특성화",
      "source_url": "https://ipsi.kangnam.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "한신대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월 본교 설명회",
      "time": "TBD",
      "location": "한신대 캠퍼스(오산)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.hs.ac.kr/",
      "fee": "무료",
      "notes": "신학·사회복지·경영·평화안보 학과 — 문과 적합",
      "source_url": "https://ipsi.hs.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "협성대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "협성대 캠퍼스(화성 봉담)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.uhs.ac.kr/",
      "fee": "무료",
      "notes": "수원대와 같은 화성 봉담권. 신학·사회복지·문화콘텐츠 등",
      "source_url": "https://ipsi.uhs.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "평택대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "평택대 캠퍼스(평택)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.ptu.ac.kr/",
      "fee": "무료",
      "notes": "수원~천안 중간 지점. 국제·관광·사회복지 등",
      "source_url": "https://admission.ptu.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "한경국립대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "한경국립대(안성/평택 캠퍼스)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.hknu.ac.kr/",
      "fee": "무료",
      "notes": "국립대. 안성 위치 — 수원~천안권. 농업·식품·웰니스 강세이나 문과도 있음",
      "source_url": "https://ipsi.hknu.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권", "국립대"],
      "priority": "medium"
    },
    {
      "university": "용인대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "용인대 캠퍼스(용인 처인)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.yongin.ac.kr/",
      "fee": "무료",
      "notes": "체육·무도 유명하나 경찰행정·문화관광 등 문과도 운영",
      "source_url": "https://ipsi.yongin.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "한국항공대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~8월",
      "time": "TBD",
      "location": "한국항공대 캠퍼스(고양 화전)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://go.kau.ac.kr/",
      "fee": "무료",
      "notes": "항공·우주·운항 등 이공계 중심이나 항공경영·항공교통도 — 문과 일부",
      "source_url": "https://go.kau.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": false,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "한성대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "한성대 캠퍼스(서울 성북)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.hansung.ac.kr/",
      "fee": "무료",
      "notes": "서울 성북. 사회과학·인문·디자인 등 문과 다수",
      "source_url": "https://ipsi.hansung.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD"],
      "priority": "low"
    },
    {
      "university": "남서울대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "남서울대 캠퍼스(천안 성환)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.nsu.ac.kr/",
      "fee": "무료",
      "notes": "천안 성환 위치. 사회복지·경영·국제·미디어 등 문과 다수",
      "source_url": "https://admission.nsu.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "백석대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "백석대 캠퍼스(천안)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.bu.ac.kr/",
      "fee": "무료",
      "notes": "천안 위치. 기독교 기반. 사회복지·법·경영·관광 등 문과",
      "source_url": "https://ipsi.bu.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "선문대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "선문대 캠퍼스(천안/아산)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.sunmoon.ac.kr/",
      "fee": "무료",
      "notes": "천안/아산. 글로벌비즈·관광·일어·중어 등 문과 강세",
      "source_url": "https://ipsi.sunmoon.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "호서대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "호서대 캠퍼스(천안/아산)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.hoseo.edu/",
      "fee": "무료",
      "notes": "천안/아산. 경영·법·사회복지·문헌정보 등 문과 다수",
      "source_url": "https://ipsi.hoseo.edu/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "low"
    },
    {
      "university": "순천향대학교",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "순천향대 캠퍼스(아산 신창)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://admission.sch.ac.kr/",
      "fee": "무료",
      "notes": "아산 위치. 의대 + 사회복지·경영·법·국제·관광 등 문과 다수",
      "source_url": "https://admission.sch.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": true,
      "tags": ["TBD", "수원~천안권"],
      "priority": "medium"
    },
    {
      "university": "한국기술교육대학교 (코리아텍)",
      "event_name": "입학설명회 (TBD)",
      "date": "TBD",
      "date_note": "예년 7~9월",
      "time": "TBD",
      "location": "코리아텍 캠퍼스(천안)",
      "format": "오프라인",
      "audience": ["학부모", "수험생"],
      "registration_required": true,
      "registration_deadline": "TBD",
      "registration_url": "",
      "info_url": "https://ipsi.koreatech.ac.kr/",
      "fee": "무료",
      "notes": "국립. 천안 소재. 공학 중심 — 인사·산업경영도 문과 일부",
      "source_url": "https://ipsi.koreatech.ac.kr/",
      "tier": "수도권_중하위",
      "humanities_relevant": false,
      "tags": ["TBD", "수원~천안권", "국립"],
      "priority": "low"
    }
  ]
}
;
